"""Create a GitHub pull request via the REST API."""

from __future__ import annotations

from urllib.parse import urlsplit

import requests

GITHUB_API = "https://api.github.com"
_TIMEOUT = 30


def _owner_repo(repo_clone_url: str) -> tuple[str, str]:
    """Extract (owner, repo) from a clone URL.

    Supports both HTTPS (``https://github.com/owner/repo.git``) and SSH-style
    (``git@github.com:owner/repo.git``) forms.
    """
    url = repo_clone_url.strip()
    if url.startswith("git@") or url.startswith("ssh://"):
        # git@github.com:owner/repo.git  -> owner/repo.git
        path = url.split(":", 1)[-1]
    else:
        path = urlsplit(url).path
    path = path.strip("/")
    if path.endswith(".git"):
        path = path[: -len(".git")]
    parts = path.split("/")
    if len(parts) < 2:
        raise ValueError(f"cannot parse owner/repo from clone URL: {repo_clone_url!r}")
    return parts[-2], parts[-1]


def create_pr(token: str, repo_clone_url: str, base_branch: str, fix_branch: str,
              ticket_id: str, ticket_url: str, summary: str,
              sonar_hash: str) -> str:
    """Open a PR from ``fix_branch`` into ``base_branch``. Returns the PR URL.

    If a PR for this head/base already exists, returns the existing PR's URL
    (idempotent at the GitHub layer).
    """
    owner, repo = _owner_repo(repo_clone_url)
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    title = f"fix: {summary} [{ticket_id}]"
    body = (
        f"Automated SonarQube remediation for **{ticket_id}**.\n\n"
        f"- Jira ticket: {ticket_url}\n"
        f"- sonar_hash: `{sonar_hash}`\n\n"
        "---\n"
        "_Generated by kiro-minions._\n"
    )

    payload = {
        "title": title,
        "head": fix_branch,
        "base": base_branch,
        "body": body,
        "maintainer_can_modify": True,
    }

    resp = requests.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
        headers=headers,
        json=payload,
        timeout=_TIMEOUT,
    )

    if resp.status_code == 201:
        return resp.json()["html_url"]

    # A PR may already exist for this head/base — find and return it.
    if resp.status_code == 422:
        existing = _find_existing_pr(headers, owner, repo, base_branch, fix_branch)
        if existing:
            return existing

    raise RuntimeError(
        f"GitHub PR creation failed ({resp.status_code}): {resp.text}"
    )


def _find_existing_pr(headers: dict, owner: str, repo: str, base_branch: str,
                      fix_branch: str) -> str | None:
    """Look up an open PR for head=fix_branch base=base_branch."""
    resp = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
        headers=headers,
        params={"state": "open", "head": f"{owner}:{fix_branch}", "base": base_branch},
        timeout=_TIMEOUT,
    )
    if resp.status_code == 200:
        items = resp.json()
        if items:
            return items[0]["html_url"]
    return None
